name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [v9-dark-theme-refinements, v9-theme-font-update, main]
  workflow_dispatch:

env:
  CI: 1
  NODE_OPTIONS: "--max-old-space-size=6144 --dns-result-order=ipv4first"

jobs:
  deploy-docs:
    name: Build and Deploy Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Setup Yarn
        run: |
          npm uninstall -g yarn
          npm i -g yarn@1.22.10
          yarn install --frozen-lockfile

      - name: Build Docs
        run: yarn build-docs

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
