name: Release Workflow

on:
  push:
    tags:
      - "*"

jobs:
  release-to-npm:
    environment: release-approval
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Setup Yarn
        run: |
          npm uninstall -g yarn
          npm i -g yarn@1.22.10
          yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - run: npm ci

      - run: npm publish

      - name: Release on Github
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
